
# This file is automatically generated, you probably don't want to edit this

binomOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "binomOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            p = "0.5",
            n1 = 10,
            n2 = 20,
            n3 = 30,
            n = 20,
            p1 = "0.5",
            p2 = "0.7",
            p3 = "0.9",
            mean = FALSE,
            std = FALSE, ...) {

            super$initialize(
                package="School",
                name="binom",
                requiresData=TRUE,
                ...)

            private$..p <- jmvcore::OptionString$new(
                "p",
                p,
                default="0.5")
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1,
                default=10)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2,
                default=20)
            private$..n3 <- jmvcore::OptionInteger$new(
                "n3",
                n3,
                default=30)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                default=20)
            private$..p1 <- jmvcore::OptionString$new(
                "p1",
                p1,
                default="0.5")
            private$..p2 <- jmvcore::OptionString$new(
                "p2",
                p2,
                default="0.7")
            private$..p3 <- jmvcore::OptionString$new(
                "p3",
                p3,
                default="0.9")
            private$..mean <- jmvcore::OptionBool$new(
                "mean",
                mean,
                default=FALSE)
            private$..std <- jmvcore::OptionBool$new(
                "std",
                std,
                default=FALSE)

            self$.addOption(private$..p)
            self$.addOption(private$..n1)
            self$.addOption(private$..n2)
            self$.addOption(private$..n3)
            self$.addOption(private$..n)
            self$.addOption(private$..p1)
            self$.addOption(private$..p2)
            self$.addOption(private$..p3)
            self$.addOption(private$..mean)
            self$.addOption(private$..std)
        }),
    active = list(
        p = function() private$..p$value,
        n1 = function() private$..n1$value,
        n2 = function() private$..n2$value,
        n3 = function() private$..n3$value,
        n = function() private$..n$value,
        p1 = function() private$..p1$value,
        p2 = function() private$..p2$value,
        p3 = function() private$..p3$value,
        mean = function() private$..mean$value,
        std = function() private$..std$value),
    private = list(
        ..p = NA,
        ..n1 = NA,
        ..n2 = NA,
        ..n3 = NA,
        ..n = NA,
        ..p1 = NA,
        ..p2 = NA,
        ..p3 = NA,
        ..mean = NA,
        ..std = NA)
)

binomResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "binomResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        valueTable1 = function() private$.items[["valueTable1"]],
        valueTable2 = function() private$.items[["valueTable2"]],
        binomPlot1 = function() private$.items[["binomPlot1"]],
        binomPlot2 = function() private$.items[["binomPlot2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Binomial Distribution")
            self$add(jmvcore::Output$new(
                options=options,
                name="text",
                title="Binomial Distribution"))
            self$add(jmvcore::Table$new(
                options=options,
                name="valueTable1",
                title="Different Size",
                rows=3,
                columns=list(
                    list(
                        `name`="sizeCol", 
                        `title`="Size", 
                        `type`="text"),
                    list(
                        `name`="probCol", 
                        `title`="Probability", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="valueTable2",
                title="Different Probability",
                rows=3,
                columns=list(
                    list(
                        `name`="sizeCol", 
                        `title`="Size", 
                        `type`="text"),
                    list(
                        `name`="probCol", 
                        `title`="Probability", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="binomPlot1",
                title="Different Size",
                width=600,
                height=300,
                clearWith=list(
                    "p",
                    "n1",
                    "n2",
                    "n3",
                    "mean",
                    "std"),
                renderFun=".binomplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="binomPlot2",
                title="Different Probability",
                width=600,
                height=300,
                clearWith=list(
                    "n",
                    "p1",
                    "p2",
                    "p3",
                    "mean",
                    "std"),
                renderFun=".binomplot"))}))

binomBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "binomBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "School",
                name = "binom",
                version = c(1,0,0),
                options = options,
                results = binomResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Different Parameters
#'
#' 
#' @param data .
#' @param p .
#' @param n1 .
#' @param n2 .
#' @param n3 .
#' @param n .
#' @param p1 .
#' @param p2 .
#' @param p3 .
#' @param mean .
#' @param std .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$valueTable1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$valueTable2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$binomPlot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$binomPlot2} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$valueTable1$asDF}
#'
#' \code{as.data.frame(results$valueTable1)}
#'
#' @export
binom <- function(
    data,
    p = "0.5",
    n1 = 10,
    n2 = 20,
    n3 = 30,
    n = 20,
    p1 = "0.5",
    p2 = "0.7",
    p3 = "0.9",
    mean = FALSE,
    std = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("binom requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- binomOptions$new(
        p = p,
        n1 = n1,
        n2 = n2,
        n3 = n3,
        n = n,
        p1 = p1,
        p2 = p2,
        p3 = p3,
        mean = mean,
        std = std)

    analysis <- binomClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

