
# This file is automatically generated, you probably don't want to edit this

histogramOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            count = "abs",
            bounds = "format",
            lowerBound = 0,
            upperBound = 20,
            bins = "numBins",
            numBinsN = 19,
            widthBinsN = 1,
            ruleBinsN = "sqrtN",
            breakBinsN = "0,1,10,20,100", ...) {

            super$initialize(
                package="School",
                name="histogram",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var)
            private$..count <- jmvcore::OptionList$new(
                "count",
                count,
                options=list(
                    "abs",
                    "prop"),
                default="abs")
            private$..bounds <- jmvcore::OptionList$new(
                "bounds",
                bounds,
                options=list(
                    "format",
                    "man"),
                default="format")
            private$..lowerBound <- jmvcore::OptionNumber$new(
                "lowerBound",
                lowerBound,
                default=0)
            private$..upperBound <- jmvcore::OptionNumber$new(
                "upperBound",
                upperBound,
                default=20)
            private$..bins <- jmvcore::OptionList$new(
                "bins",
                bins,
                options=list(
                    "numBins",
                    "widthBins",
                    "ruleBins",
                    "breakBins"),
                default="numBins")
            private$..numBinsN <- jmvcore::OptionInteger$new(
                "numBinsN",
                numBinsN,
                default=19)
            private$..widthBinsN <- jmvcore::OptionNumber$new(
                "widthBinsN",
                widthBinsN,
                default=1)
            private$..ruleBinsN <- jmvcore::OptionList$new(
                "ruleBinsN",
                ruleBinsN,
                options=list(
                    "sqrtN",
                    "logN"),
                default="sqrtN")
            private$..breakBinsN <- jmvcore::OptionString$new(
                "breakBinsN",
                breakBinsN,
                default="0,1,10,20,100")

            self$.addOption(private$..var)
            self$.addOption(private$..count)
            self$.addOption(private$..bounds)
            self$.addOption(private$..lowerBound)
            self$.addOption(private$..upperBound)
            self$.addOption(private$..bins)
            self$.addOption(private$..numBinsN)
            self$.addOption(private$..widthBinsN)
            self$.addOption(private$..ruleBinsN)
            self$.addOption(private$..breakBinsN)
        }),
    active = list(
        var = function() private$..var$value,
        count = function() private$..count$value,
        bounds = function() private$..bounds$value,
        lowerBound = function() private$..lowerBound$value,
        upperBound = function() private$..upperBound$value,
        bins = function() private$..bins$value,
        numBinsN = function() private$..numBinsN$value,
        widthBinsN = function() private$..widthBinsN$value,
        ruleBinsN = function() private$..ruleBinsN$value,
        breakBinsN = function() private$..breakBinsN$value),
    private = list(
        ..var = NA,
        ..count = NA,
        ..bounds = NA,
        ..lowerBound = NA,
        ..upperBound = NA,
        ..bins = NA,
        ..numBinsN = NA,
        ..widthBinsN = NA,
        ..ruleBinsN = NA,
        ..breakBinsN = NA)
)

histogramResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramResults",
    inherit = jmvcore::Group,
    active = list(
        hist = function() private$.items[["hist"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Histogramm")
            self$add(jmvcore::Image$new(
                options=options,
                name="hist",
                title="Histogram Plot",
                width=400,
                height=300,
                renderFun=".histogram"))}))

histogramBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "School",
                name = "histogram",
                version = c(1,0,0),
                options = options,
                results = histogramResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Histogramm
#'
#' 
#' @param data .
#' @param var .
#' @param count \code{'abs'} (default) , \code{'prop'}. Choose wether to use
#'   absolute count or proportions on the y-axis
#' @param bounds \code{'format'} (default) , \code{'man'}. Choose wether to
#'   use set bounds for x-axis manually or format by rule
#' @param lowerBound .
#' @param upperBound .
#' @param bins \code{'numBins'} (default) , \code{'breakBins'} ,
#'   \code{'ruleBins'} or \code{'widthBins'}. Define Number of Bins, set
#'   Breakpoints manually, use rule of thumb or use binWidth , respectively
#' @param numBinsN .
#' @param widthBinsN .
#' @param ruleBinsN .
#' @param breakBinsN .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$hist} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
histogram <- function(
    data,
    var,
    count = "abs",
    bounds = "format",
    lowerBound = 0,
    upperBound = 20,
    bins = "numBins",
    numBinsN = 19,
    widthBinsN = 1,
    ruleBinsN = "sqrtN",
    breakBinsN = "0,1,10,20,100") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("histogram requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL))


    options <- histogramOptions$new(
        var = var,
        count = count,
        bounds = bounds,
        lowerBound = lowerBound,
        upperBound = upperBound,
        bins = bins,
        numBinsN = numBinsN,
        widthBinsN = widthBinsN,
        ruleBinsN = ruleBinsN,
        breakBinsN = breakBinsN)

    analysis <- histogramClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

