
# This file is automatically generated, you probably don't want to edit this

htestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "htestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            p0 = "0.5",
            n = 20,
            k = 5,
            side = "leftSide",
            alpha = "0.05",
            showHypoPlot = TRUE,
            kLine = TRUE,
            scaleX = TRUE,
            expl = TRUE,
            showErrorPlot = FALSE,
            p = "0.7", ...) {

            super$initialize(
                package="School",
                name="htest",
                requiresData=TRUE,
                ...)

            private$..p0 <- jmvcore::OptionString$new(
                "p0",
                p0,
                default="0.5")
            private$..n <- jmvcore::OptionNumber$new(
                "n",
                n,
                default=20)
            private$..k <- jmvcore::OptionNumber$new(
                "k",
                k,
                default=5)
            private$..side <- jmvcore::OptionList$new(
                "side",
                side,
                options=list(
                    "leftSide",
                    "bothSides",
                    "rightSide"),
                default="leftSide")
            private$..alpha <- jmvcore::OptionString$new(
                "alpha",
                alpha,
                default="0.05")
            private$..showHypoPlot <- jmvcore::OptionBool$new(
                "showHypoPlot",
                showHypoPlot,
                default=TRUE)
            private$..kLine <- jmvcore::OptionBool$new(
                "kLine",
                kLine,
                default=TRUE)
            private$..scaleX <- jmvcore::OptionBool$new(
                "scaleX",
                scaleX,
                default=TRUE)
            private$..expl <- jmvcore::OptionBool$new(
                "expl",
                expl,
                default=TRUE)
            private$..showErrorPlot <- jmvcore::OptionBool$new(
                "showErrorPlot",
                showErrorPlot,
                default=FALSE)
            private$..p <- jmvcore::OptionString$new(
                "p",
                p,
                default="0.7")

            self$.addOption(private$..p0)
            self$.addOption(private$..n)
            self$.addOption(private$..k)
            self$.addOption(private$..side)
            self$.addOption(private$..alpha)
            self$.addOption(private$..showHypoPlot)
            self$.addOption(private$..kLine)
            self$.addOption(private$..scaleX)
            self$.addOption(private$..expl)
            self$.addOption(private$..showErrorPlot)
            self$.addOption(private$..p)
        }),
    active = list(
        p0 = function() private$..p0$value,
        n = function() private$..n$value,
        k = function() private$..k$value,
        side = function() private$..side$value,
        alpha = function() private$..alpha$value,
        showHypoPlot = function() private$..showHypoPlot$value,
        kLine = function() private$..kLine$value,
        scaleX = function() private$..scaleX$value,
        expl = function() private$..expl$value,
        showErrorPlot = function() private$..showErrorPlot$value,
        p = function() private$..p$value),
    private = list(
        ..p0 = NA,
        ..n = NA,
        ..k = NA,
        ..side = NA,
        ..alpha = NA,
        ..showHypoPlot = NA,
        ..kLine = NA,
        ..scaleX = NA,
        ..expl = NA,
        ..showErrorPlot = NA,
        ..p = NA)
)

htestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "htestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        todo = function() private$.items[["todo"]],
        table = function() private$.items[["table"]],
        hypoPlot = function() private$.items[["hypoPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Hypothesis Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Explanation",
                visible="(expl)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="Explanation",
                visible="(expl)",
                clearWith=list(
                    "side",
                    "alpha",
                    "p0",
                    "expl")))
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Binomial Test",
                clearWith=list(
                    "p0",
                    "n",
                    "k",
                    "side",
                    "alpha"),
                columns=list(
                    list(
                        `name`="label", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="result", 
                        `title`="Result", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="hypoPlot",
                title="",
                visible="(showHypoPlot)",
                clearWith=list(
                    "p0",
                    "n",
                    "k",
                    "side",
                    "alpha",
                    "kLine",
                    "scaleX",
                    "showHypoPlot"),
                width=600,
                height=400,
                renderFun=".hypoPlot"))}))

htestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "htestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "School",
                name = "htest",
                version = c(1,0,0),
                options = options,
                results = htestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Binomial Hypothesis Test
#'
#' 
#' @param data .
#' @param p0 .
#' @param n .
#' @param k .
#' @param side \code{'leftSide'} (default) , \code{'bothSides'} ,
#'   \code{'rightSide'}. Decide on which Side you want to take the test
#' @param alpha .
#' @param showHypoPlot .
#' @param kLine .
#' @param scaleX .
#' @param expl .
#' @param showErrorPlot .
#' @param p .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table of the test results \cr
#'   \code{results$hypoPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
htest <- function(
    data,
    p0 = "0.5",
    n = 20,
    k = 5,
    side = "leftSide",
    alpha = "0.05",
    showHypoPlot = TRUE,
    kLine = TRUE,
    scaleX = TRUE,
    expl = TRUE,
    showErrorPlot = FALSE,
    p = "0.7") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("htest requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- htestOptions$new(
        p0 = p0,
        n = n,
        k = k,
        side = side,
        alpha = alpha,
        showHypoPlot = showHypoPlot,
        kLine = kLine,
        scaleX = scaleX,
        expl = expl,
        showErrorPlot = showErrorPlot,
        p = p)

    analysis <- htestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

